# Double and mock definitions aren't recognized as macros.
# These "useless" variable assignments are very much used.
Lint/UselessAssign:
  Description: Disallows useless variable assignments
  Excluded:
    - spec/**/*.cr
  Enabled: true
  Severity: Warning

# The scope spec uses non-nil to (lazily) ensure a shared instance is initialized before a test.
Lint/NotNil:
  Excluded:
    - spec/mocks/scope_spec.cr
  Enabled: true
