image: "crystallang/crystal:latest"

before_script:
  - shards install

cache:
  paths:
  - lib/
  - bin/

spec:
  script:
  - crystal spec

nightly:
  image: "crystallang/crystal:nightly"
  allow_failure: true
  script:
  - crystal spec

lint:
  script:  
  - crystal tool format --check
  - bin/ameba

pages:
  stage: deploy
  script:
  - crystal docs -o public src/mocks.cr
  artifacts:
    paths:
    - public
  only:
  - master
